# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0002_auto_20171122_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
