# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0003_auto_20180220_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
